### ISSUE TITLE
Sign in non-functional

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#107]
### Context

* Operating system: Pex 
* Browser: chrome
* Phone / Device description (Make/Model/Form factor): 15 inch laptop
* If testing on online demo, URL: http://192.237.248.135:10020/user/#/signin

### Observed behavior

Signing in does not work

### Expected behavior

Upon entering the correct login details, I expect to be directed to the page where I choose my Profile

### Steps to reproduce

1. As an admin, create a learner account
2. Log out
3. Sign in with login details
4. Get error message

![image](https://user-images.githubusercontent.com/5150483/32757565-021520fe-c895-11e7-9296-c1e44b1e8490.png)

### Errors and logs

Relevant errors and tracebacks from:

* the command line
* `~/.kolibri/kolibri.log`
* the browser console

```
server logs
```

```
browser console logs
```

**Comment by jeepurs** [comment]
Note that @aronasorman already removed the user plugin and used the vf plugin

**Comment by jeepurs** [comment]
Note that sign in is functional only when the learner created their own account, not when an admin creates an account

**Comment by indirectlylit** [comment]
I believe this has been addressed
