### ISSUE TITLE
Create Account non-functional

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#108]
### Context

* Operating system: pex
* Browser: Chrome
* Phone / Device description (Make/Model/Form factor): 15 inch laptop
* If testing on online demo, URL: http://192.237.248.135:10020/user/#/create_account

### Observed behavior

After entering in account creation details, I received the error message that something went wrong.

### Expected behavior

I expected to get autodirected after I finish creating an account

### Steps to reproduce

1. From the sign in page, click on Create Account
2. Enter in details to create account
3. Click on checkbox for TOS
4. Click on Finish

![image](https://user-images.githubusercontent.com/5150483/32757630-49f32a74-c895-11e7-9ea2-dc2f326ea62d.png)

### Errors and logs

Relevant errors and tracebacks from:

* the command line
* `~/.kolibri/kolibri.log`
* the browser console

```
server logs
```

```
browser console logs
```

**Comment by jeepurs** [comment]
Note that @aronasorman already removed the user plugin and used the vf plugin

**Comment by christianmemije** [comment]
@aronasorman Try `kolibri manage migrate`

**Comment by indirectlylit** [comment]
this appears to have been addressed
