### ISSUE TITLE
Logo on signup page needs to be IS

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#111]
### Observed behavior

Kolibri logo

### Expected behavior

IS logo

**Comment by christianmemije** [comment]
This issue does not exist on the the develop branch. You might have been testing an old pex.

Currently:

![localhost_8000_user_ 9](https://user-images.githubusercontent.com/7193975/32802330-82b6fbe8-c934-11e7-9d32-4009d80729cb.png)

**Comment by DXCanas** [comment]
Closing for now. Should be resolved once pex is properly built.
