### ISSUE TITLE
Videos do not load on some devices.

### ISSUE THREAD

**Issue by christianmemije** [fle-internal/kolibri-instant-schools-plugin#116]
### Context

* Operating system: Android
* Browser: Chrome
* Phone / Device description: Vodacom Smart Kicka ve (AP5)

### Observed behavior

Video player never loads. Issue with the `loadedmetadata` event listener, which should trigger the `handleReadyPlayer` function.

### Expected behavior

Video player loads

### Steps to reproduce

Attempt to load a video on that device.

### User-facing consequences

:disappointed: 

### Errors and logs

None

**Comment by indirectlylit** [comment]
this should be fixed in by the PR above
