### ISSUE TITLE
Disable autofocus for mobile keyboards

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#118]
### Context

* Operating system: Online demo
* Browser: Android 7.0 / Chrome browser
* Phone / Device description (Make/Model/Form factor): Samsung Galaxy A3 4.7” screen
* If testing on online demo, URL: 

### Observed behavior

When you are asked for your phone number and keyboard pops up, you do not see Create Account etc unless you think to scroll down.

### Expected behavior

To see all options and reduce scrolling. Suggestion: disable autofocus

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5150483/32896378-bbfc4a34-ca97-11e7-9d03-2f8cefb857af.png)

**Comment by indirectlylit** [comment]
Note that this only seems to be an issue if they navigate 'back' from the profile selection page.

If we can improve the UX of that (see #129) this issue might not be important to fix. Leaving the milestone off for now.

**Comment by indirectlylit** [comment]
closing since #129 is addressed
