### ISSUE TITLE
Suggestion: Forced visibility of scrollbar on sign in page

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#119]
### Context

* Operating system: Online demo
* Browser: Android 7.0 / Chrome browser
* Phone / Device description (Make/Model/Form factor): Samsung Galaxy A3 4.7” screen
* If testing on online demo, URL: 

### Observed behavior

When you are asked for your phone number and keyboard pops up, you do not see Create Account etc unless you think to scroll down.

### Expected behavior

To see all options including Create Account and Access as Guest

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5150483/32896378-bbfc4a34-ca97-11e7-9d03-2f8cefb857af.png)

**Comment by indirectlylit** [comment]
migrated to https://github.com/learningequality/clearinghouse/issues/65
