### ISSUE TITLE
Implement fixed position dropdown

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#120]
### Context

* Operating system: Online demo
* Browser: Android 7.0 / Chrome browser
* Phone / Device description (Make/Model/Form factor): Samsung Galaxy A3 4.7” screen
* If testing on online demo, URL: 

### Observed behavior

Right hand side dropdown menu is cut off, especially for "Change language"

### Expected behavior

To see all options in the dropdown menu

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5150483/32896604-56652898-ca98-11e7-9cdf-62538700b279.png)

**Comment by indirectlylit** [comment]
migrating this issue to https://github.com/learningequality/kolibri/issues/1206, which is now retargeted to 0.6.1
