### ISSUE TITLE
prevent Chrome browser translation options

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#121]
### Context

* Operating system: Online demo
* Browser: Android 7.0 / Chrome browser
* Phone / Device description (Make/Model/Form factor): Samsung Galaxy A3 4.7” screen
* If testing on online demo, URL:

### Observed behavior

Chrome browser translation option pop up, confusing the learner as to which language switcher to use.

### Expected behavior

To have user see Kolibri options for language switching

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5150483/32896728-a834a752-ca98-11e7-9af7-d81d1d1b1608.png)

### Errors and logs

**Comment by indirectlylit** [comment]
migrated to https://github.com/learningequality/kolibri/issues/2617
