### ISSUE TITLE
Improvements to topic cards: Reduce font size and make thumbnail smaller

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#122]
### Context

* Operating system: Online demo
* Browser: Android 7.0 / Chrome browser
* Phone / Device description (Make/Model/Form factor): Samsung Galaxy A3 4.7” screen
* If testing on online demo, URL:

### Observed behavior

Topics cards: End of content names cut off. The fact that thumbnails are very big does not help with this

### Expected behavior

Cards should look good down to 320x480

### Steps to reproduce

see on small screen

![image](https://user-images.githubusercontent.com/5150483/32896822-e6aad268-ca98-11e7-8691-86b62af0362e.png)

**Comment by indirectlylit** [comment]
lower priority since we've already made some improvements, but could be a relatively fast change

**Comment by indirectlylit** [comment]
see also https://github.com/learningequality/kolibri/issues/2193

**Comment by indirectlylit** [comment]
migrated to https://github.com/learningequality/kolibri/issues/2781
