### ISSUE TITLE
quick fix to Perseus exercise responsiveness - adding overflow: scroll

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#123]
### Context

* Operating system: Online demo
* Browser: Android 7.0 / Chrome browser
* Phone / Device description (Make/Model/Form factor): Samsung Galaxy A3 4.7” screen
* If testing on online demo, URL:

### Observed behavior

Perseus (Khan Academy) exercises aren't viewable on the entire mobile screen

### Expected behavior

To be able to access the entire area where Perseus exercise is on the page, it should scroll horizontally

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5150483/32896977-47f77e2c-ca99-11e7-9335-d05d32b1949e.png)

**Comment by indirectlylit** [comment]
migrating to https://github.com/learningequality/kolibri/issues/2628
