### ISSUE TITLE
Fixes to Perseus: Z-index and adding bottom margin to content

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#124]
### Context

* Operating system: Online demo
* Browser: Android 7.0 / Chrome browser
* Phone / Device description (Make/Model/Form factor): Samsung Galaxy A3 4.7” screen
* If testing on online demo, URL:

### Observed behavior

* Perseus (Khan Academy) exercise views are inconsistent on mobile.
* Mastery progress isn't visible when at the top of the screen.
* Arrow from carousel overflows into bottom margin.
* Perseus images overflow into bottom margin.

### Expected behavior

content is not obscured and layering orders are correct

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5150483/32897068-7e83f416-ca99-11e7-97cc-c2b4922b07ad.png)

### User-facing consequences

broken looking UI, and some content obscured

**Comment by indirectlylit** [comment]
migrating to https://github.com/learningequality/kolibri/issues/2630
