### ISSUE TITLE
Suggestion: make successful answer messaging clearer and distinguish from mastery

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#125]
### Context

* Operating system: Online demo
* Browser: Android 7.0 / Chrome browser
* Phone / Device description (Make/Model/Form factor): Samsung Galaxy A3 4.7” screen
* If testing on online demo, URL:

### Observed behavior

Check button isn't clearly distinguished (i.e. not a primary button).
Next question is a primary button, but doesn't show up until after mastery.

### Expected behavior

Check button is a primary button, not a secondary button.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5150483/32897361-39511f80-ca9a-11e7-9fb4-2247c485bb76.png)

**Comment by indirectlylit** [comment]
migrating to https://github.com/learningequality/kolibri/issues/2618
