### ISSUE TITLE
Suggestion: Options on Profile selection page (Exit vs. Back arrow)

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#127]
### Context

* Operating system: Online demo
* Browser: Android 7.0 / Chrome browser
* Phone / Device description (Make/Model/Form factor): Samsung Galaxy A3 4.7” screen
* If testing on online demo, URL:

### Observed behavior

Only available option, if a user doesn't realize the profile cards are selectable, is the back arrow, causing confusion

### Expected behavior

Clear selection card action.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5150483/32897532-c283c302-ca9a-11e7-9cec-fb6255284c85.png)

**Comment by indirectlylit** [comment]
addressed in #141
