### ISSUE TITLE
Suggestion: Auto-redirect after Profile creation

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#128]
### Context

* Operating system: Online demo
* Browser: Android 7.0 / Chrome browser
* Phone / Device description (Make/Model/Form factor): Samsung Galaxy A3 4.7” screen
* If testing on online demo, URL:

### Observed behavior

After making profile, the user is expected to select their own profile.  If the selection CTA is not clear to the user, this causes confusion

### Expected behavior

Getting taken straight to 'About' page after making profile

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5150483/32897532-c283c302-ca9a-11e7-9cec-fb6255284c85.png)

**Comment by indirectlylit** [comment]
> If the selection CTA is not clear to the user, this causes confusion

CTA should be more clear with #141
