### ISSUE TITLE
Make it clearer that cards are clickable

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#129]
### Observed behavior

A user doesn't realize the profile cards are selectable. On this screen, one user commented "only option is to click back arrow":

![image](https://user-images.githubusercontent.com/2367265/32908807-88551f90-cab9-11e7-9f48-870a2a9d79ac.png)

The other issue is that 'New profile' is the primary option, whereas usually someone will select a new profile.

### Expected behavior

It should be glaringly obvious what to do.

One obvious issue is the cards above don't have white backgrounds. Changing this would look like:

![image](https://user-images.githubusercontent.com/2367265/32908783-757c8bd8-cab9-11e7-8172-85c172de3200.png)

However, the cards are still not standard UI elements that new users would be familiar with. Maybe it's safer just to use standard buttons?

![image](https://user-images.githubusercontent.com/2367265/32908693-2a09ec04-cab9-11e7-84fb-2c3297ea9e08.png)

### User-facing consequences

Users don't know how to proceed at a critical step

**Comment by jtamiace** [comment]
.... What testing is this feedback based on?

**Comment by indirectlylit** [comment]
It was feedback from one user. But even one data point seems like a big flag: since this is a critical path, we shouldn't sacrifice usability for aesthetics.

**Comment by indirectlylit** [comment]
(I'm definitely open to further testing, but figured it was easiest to just squeeze something in quickly)

**Comment by jtamiace** [comment]
By this logic, users shouldn't think that content cards are clickable either. I'm betting that changing the color to white would help, and also be consistent with content cards. 

I don't have the grounds for knowing whether or not profile cards with a stronger contrast from the background is sufficiently usable, though

**Comment by indirectlylit** [comment]
that's fair.

Just an aside - the cards might seem less similar to typical users than they do to us. We "know" they're the "same", but they actually look quite different :)

![image](https://user-images.githubusercontent.com/2367265/32962673-2b4cf664-cb82-11e7-8217-9d87f6fa91d5.png)

![image](https://user-images.githubusercontent.com/2367265/32962696-4a11e3c0-cb82-11e7-81bf-6ab32d41416f.png)
