### ISSUE TITLE
Remove filtering out of Topics and other places where there isn't a flat list

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#132]
### Context

* Operating system: Online demo
* Browser: Android 7.0 / Chrome browser
* Phone / Device description (Make/Model/Form factor): Samsung Galaxy A3 4.7” screen
* If testing on online demo, URL:

### Observed behavior

Filtering is already removed from Recommended.  

### Expected behavior

To remove filtering from all areas where there isn't a flat list of content

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5150483/32898054-f37da6ca-ca9b-11e7-97c0-4e5919e931c3.png)

**Comment by indirectlylit** [comment]
migrated to https://github.com/learningequality/kolibri/issues/2619
