### ISSUE TITLE
Change 'Topics' to 'Channels'

### ISSUE THREAD

**Issue by jeepurs** [fle-internal/kolibri-instant-schools-plugin#133]
### Context

* Operating system: Online demo
* Browser: Android 7.0 / Chrome browser
* Phone / Device description (Make/Model/Form factor): Samsung Galaxy A3 4.7” screen
* If testing on online demo, URL:

### Observed behavior

Confusion around topic vs. channel 

### Expected behavior

Channel is consistent with how it is viewed in Studio.  

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5150483/32898171-46b5a39c-ca9c-11e7-828b-695c3426af88.png)

**Comment by indirectlylit** [comment]
migrated to https://github.com/learningequality/kolibri/issues/2621
