### ISSUE TITLE
"Password" placeholder in the sign-in page on mobile

### ISSUE THREAD

**Issue by radinamatic** [fle-internal/kolibri-instant-schools-plugin#145]
### Context

* Operating system: Android 6.0.1, 4.2.2
* Browser: Chrome
* Phone / Device description (Make/Model/Form factor): not sure of the original reporter's make / model, but happens both on my MotoG Play (Android 6.0.1) and Samsung GT-S7580 (Android 4.2.2)
* Online demo, URL: https://instantschools-v2.learningequality.org

### Observed behavior

The password field is filled in with gray wording.  Happens only in Chrome, not on Firefox.

#### Chrome
![2017_11_22_18 52 45](https://user-images.githubusercontent.com/1457929/33143123-2297513c-cfb9-11e7-8da4-b89b5dfb5f99.png)

#### Firefox
![2017_11_22_18 52 31](https://user-images.githubusercontent.com/1457929/33143173-50f36336-cfb9-11e7-8183-1f5ced47f0a5.png)

### Expected behavior

Not use the label as a placeholder for the input field.

**Comment by christianmemije** [comment]
Possible workarounds:

https://github.com/mui-org/material-ui/issues/718

**Comment by radinamatic** [comment]
Replaced by https://github.com/learningequality/kolibri/issues/2673
