### ISSUE TITLE
"Create account" button styling on the sign-in page

### ISSUE THREAD

**Issue by radinamatic** [fle-internal/kolibri-instant-schools-plugin#146]
### Context

* Operating system: all
* Browser: all
* Phone / Device description (Make/Model/Form factor): all
* If testing on online demo, URL: https://instantschools-v2.learningequality.org

### Requested change

Apply the same white-on-red styling to the `CREATE ACCOUNT` button as it is for `SIGN IN`.
`ACCESS AS A GUEST` to remain white-on-gray.

![user sign in - kolibri - google chrome_064](https://user-images.githubusercontent.com/1457929/33143676-e58441ea-cfba-11e7-827a-dedb6c06ab09.png)

**Comment by indirectlylit** [comment]
just want to point out that this would violate our style guide, which says "There should only be one primary button visible at a time"

**Comment by radinamatic** [comment]
Right, I knew I was forgetting something there...

What other options do we have? Partner's idea was to give more spotlight to the `CREATE ACCOUNT` option compared to `ACCESS AS A GUEST`, how can we better differentiate them?
cc @jeepurs

**Comment by jtamiace** [comment]
Agreed with Devon and I don't think that there should be more than one primary.
One thing we can do is stack the buttons, and use a flat button for "access as guest"?

But i don't really know if we should do that... 

Another option is to stack the buttons, keep the secondary color, and have "create account" the first option?

Would like to know the partner's reasoning for giving more spotlight though?

<img width="748" alt="screen shot 2017-11-22 at 12 11 28 pm" src="https://user-images.githubusercontent.com/6668144/33147846-4fa24ad2-cf7e-11e7-983a-ae8c9c95f461.png">

**Comment by jtamiace** [comment]
One more option: same layout with buttons inline, "access as guest" is a flat button 

<img width="353" alt="screen shot 2017-11-22 at 12 20 45 pm" src="https://user-images.githubusercontent.com/6668144/33148171-98529b78-cf7f-11e7-9030-1325d6183958.png">

**Comment by jeepurs** [comment]
Partner's reasoning for spotlighting is bc currently thousands use Instant Schools as a guest and only hundreds actually register and they'd like to encourage more account creation to capture content usage a bit better

**Comment by radinamatic** [comment]
> Would like to know the partner's reasoning for giving more spotlight though?

Because they don't want people to browse the platform as guests, they want to encourage visitors to register, for data collection. For the same reason there was an alert included here:

![counting with small numbers - khan academy en - kolibri - google chrome_070](https://user-images.githubusercontent.com/1457929/33151331-f4282028-cfd7-11e7-9bb8-1690156e55ed.png)

**Comment by radinamatic** [comment]
Ah, and @jeepurs beat me to it... :stuck_out_tongue:

**Comment by jtamiace** [comment]
I see... Maybe there are things down the line that we can do to further incentivize users to create accounts, along the same line as the message on the sign in message for guests and the points popup https://github.com/learningequality/kolibri/pull/2571

Sprinkling in messages about how they're losing out on a better experience throughout the platform. Like in content rec, a message about getting better content or something (don't take this message seriously)

I think this would be a nice opportunity to test and carry over learnings to Kolibri about the "single family/user" use case

**Comment by indirectlylit** [comment]
+1 for this strategy:

![image](https://user-images.githubusercontent.com/2367265/33246887-b400beb6-d2ce-11e7-86a5-e12427f4feb8.png)

**Comment by indirectlylit** [comment]
clearing assignees until we actually figure out what we're doing and someone has decided to work on it

**Comment by indirectlylit** [comment]
> Khang Mach: yes lets go with that one
