### ISSUE TITLE
Language switcher wording

### ISSUE THREAD

**Issue by radinamatic** [fle-internal/kolibri-instant-schools-plugin#148]
### Context

* Operating system: all
* Browser: all
* Phone / Device description (Make/Model/Form factor): all
* If testing on online demo, URL: https://instantschools-v2.learningequality.org

### Observed behavior

Language switcher wording in the modal still says “Kolibri”.

![learn - kolibri - google chrome_066](https://user-images.githubusercontent.com/1457929/33144487-825376ec-cfbd-11e7-9c7e-df61e6f3ea2e.png)

### Expected behavior

Change language switcher wording in the modal to “Instant Schools”.

**Comment by christianmemije** [comment]
It might be worth to search for other places where we use Kolibri within strings. There are some places that can do without the name, such as here. Also can we define some sort of BRAND_NAME that can be referenced and overridden @rtibbles ?

**Comment by rtibbles** [comment]
This is definitely a case where the string could just be more concise certainly. However, I am reluctant to fix this at all, as we would have to violate the string freeze.

**Comment by radinamatic** [comment]
If “Instant Schools” is a brand name, it would not even get translated, correct?

**Comment by rtibbles** [comment]
We would have to change the base string, which would then invalidate the current translation. Also, this text exists on the main Kolibri repo, so we would have to add additional ability to parameterize the 'BRAND_NAME'.

The best solution to this is to truncate the string so that we don't have to do any of that work for the BRAND_NAME, but this still violates the string freeze.

**Comment by indirectlylit** [comment]
The entire string could be hidden. Since the title already says "Change language", the rest of the text seems superfluous

**Comment by radinamatic** [comment]
That's a good point @indirectlylit ! 👍 
That wouldn't violate the string freeze, right?
