### ISSUE TITLE
Errors in the signup page.

### ISSUE THREAD

**Issue by jamalex** [fle-internal/kolibri-instant-schools-plugin#173]
### Observed behavior

Under specific circumstances, a user would experience errors trying to use the signup page.

![image](https://user-images.githubusercontent.com/618416/143309204-a62c0f95-a116-4910-96a4-9fb6d9de66c7.png)

Source: https://learningequality.slack.com/archives/CN9S5A5EG/p1637775177028100

### Expected behavior

- When trying to sign up with a phone number that already exists, should receive a meaningful error (validation) message.
- When navigating directly to the signup page (or refreshing it once there), signing up should still work.

### Steps to reproduce

- Try re-registering with an account that already exists.
- Refresh the signup page and then try signing up.

**Comment by nucleogenesis** [comment]
This has all been reworked since this point and QA passed
