### ISSUE TITLE
Main navigation - The hover effect is too dark

### ISSUE THREAD

**Issue by pcenov** [fle-internal/kolibri-instant-schools-plugin#205]
## Observed behavior

When I hover over a tab in the main navigation then it gets too dark which is making the label hard to read:

https://github.com/user-attachments/assets/69a2732e-049c-41c1-bf5c-9e0e3cec14d5

## Expected behavior

The hover effect should less pronounced. 

## Steps to reproduce the issue

1. Go to https://vodafone-staging.learningequality.org/
2. Sign in
3. Hover over any tab in the main navigation

## Usage Details
Windows 11 and Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
This is an accessibility issue, as the color contrast is failing required minimum threshold (this is not large text).

![Image](https://github.com/user-attachments/assets/018b9656-b57b-4fa7-bcb3-43bc142d1255)
