### ISSUE TITLE
Facility > Data - The export and import of .csv files is not working

### ISSUE THREAD

**Issue by pcenov** [fle-internal/kolibri-instant-schools-plugin#206]
## Observed behavior

The export and import of .csv files is not working for both the usage data logs and the import/export of users:

https://github.com/user-attachments/assets/c15b9832-2315-4232-9444-e7c60a6b541b

## Expected behavior

Fully functional export/import of .csv files.

## Steps to reproduce the issue

1. Go to https://vodafone-staging.learningequality.org/
2. Sign in as a super admin
3. Go to Facility > Data and attempt to export any of the logs, or import/export users.

## Usage Details
Windows 11 and Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by nucleogenesis** [comment]
This is related to https://github.com/learningequality/kolibri/issues/9441 I think, so no fix presently available.

Important to note that this feature landing in Kolibri we should consider updating IS again as this is likely a desirable feature
