### ISSUE TITLE
The 'About' page is not rendered correctly

### ISSUE THREAD

**Issue by pcenov** [fle-internal/kolibri-instant-schools-plugin#207]
## Observed behavior

The 'About' page is not rendered correctly:

https://github.com/user-attachments/assets/4ddad6e8-3848-4575-a72a-8b6d35f8e0a0

## Expected behavior

Functional 'About' page

## Steps to reproduce the issue

1. Go to https://vodafone-staging.learningequality.org/
2. Sign in as a super admin
3. Go to the 'About' page

## Usage Details
Windows 11 and Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
Error message in Firefox;, with bunch of errors in the console:

![Image](https://github.com/user-attachments/assets/c93ef0d9-5c0b-469c-87cd-7d952e628485)

**Comment by nucleogenesis** [comment]
I'm wondering if this might be due to the content not being set on the server itself. I'm not able to log in as the admin there at this point, but I'll test and work to resolve this once I do.
