### ISSUE TITLE
port old VF functionality

### ISSUE THREAD

**Issue by indirectlylit** [fle-internal/kolibri-instant-schools-plugin#53]
Target the `develop` branch.

Port over old functionality:

* Login
  * Phone number as username
  * Password reset pop-up 
* Sign-up
  * Phone number as username
  * validation
  * Terms of Use modal + checkbox 
* Profile
  * ‘user’ field hidden

reference: https://github.com/fle-internal/kolibri-instant-schools-plugin/pull/51/files

**Comment by DXCanas** [comment]
* Login
  - [ ] Phone number as username
  - [ ] Password reset pop-up 
* Sign-up
  - [ ] Phone number as username
  - [ ] validation
  - [ ] Terms of Use modal + checkbox 
* Profile
  - [ ] ‘user’ field hidden

**Comment by christianmemije** [comment]
Implemented in a few PRS,
