### ISSUE TITLE
SMS-based password reset functionality

### ISSUE THREAD

**Issue by indirectlylit** [fle-internal/kolibri-instant-schools-plugin#54]
see the password reset flow - [middle row in this mockup](https://files.slack.com/files-pri/T0KT5DC58-F7KJYHJGK/vf_plugin_updates_v3.png?pub_secret=00761deb00)

main user-facing elements:

* reset password modal with 'message sent' confirmation
* reset target page with link `{host}/user/#/passwordreset/{token}/{phone}`

**Comment by christianmemije** [comment]
Implemented in #70
