### ISSUE TITLE
multiple profiles per phone number

### ISSUE THREAD

**Issue by indirectlylit** [fle-internal/kolibri-instant-schools-plugin#55]
[all mockups here](https://files.slack.com/files-pri/T0KT5DC58-F7KJYHJGK/vf_plugin_updates_v3.png?pub_secret=00761deb00) but relevant details below:

Login in:

![image](https://user-images.githubusercontent.com/2367265/31691724-e148354a-b34b-11e7-8c58-f7b243c4e702.png)

Choose profile or create new:

![image](https://user-images.githubusercontent.com/2367265/31691741-f82d489a-b34b-11e7-9a5b-03434110ddcb.png)

New profile creation:

![image](https://user-images.githubusercontent.com/2367265/31691754-0351ceda-b34c-11e7-8300-433fbaa4a465.png)

Profile page with name and password editing:

![image](https://user-images.githubusercontent.com/2367265/31691768-10ba6e74-b34c-11e7-9f27-f568e3c7a782.png)

TBD: can we do password editing here?

**Comment by christianmemije** [comment]
Implemented in #72
