### ISSUE TITLE
add logo to app bar

### ISSUE THREAD

**Issue by indirectlylit** [fle-internal/kolibri-instant-schools-plugin#57]
![image](https://user-images.githubusercontent.com/2367265/31692477-be2eb6ee-b34e-11e7-8269-65052766140f.png)

**Comment by christianmemije** [comment]
Is this just within the Learn plugin?

**Comment by christianmemije** [comment]
I'm thinking that what we can do is add the icon url to the store and then within app-bar or core-base check if a url exists. If so, render that image. Thoughts?

**Comment by christianmemije** [comment]
Addressed in #63
