### ISSUE TITLE
Have profile page use special endpoint for 'FacilityUserProfiles'

### ISSUE THREAD

**Issue by jonboiser** [fle-internal/kolibri-instant-schools-plugin#78]
#62 implements a special endpoint that actually will reset the password for all users/profiles under a phone number when one of those users/profiles initiates a password change.

Currently, the sign-up page still uses the endpoint that will only modify the model for the user currently logged in (and will actually log them out).

Also, the `editPRofile` action in action.js has the password-changing logic commented out.

**Comment by christianmemije** [comment]
Addressed in #90
