### ISSUE TITLE
Profile has 2 different meanings

### ISSUE THREAD

**Issue by christianmemije** [fle-internal/kolibri-instant-schools-plugin#95]
Profile now has 2 different meanings which is likely to cause a confusing user experience.

Suggestions
Change profile page to `account` page.
In account page, display phone number.
Instead of `Full Name`, show `Profile Name`

Issues
~Profiles cannot be deleted.~
~No way to 'switch profiles'. Need to sign out and the sign back in and choose profile.~

**Comment by jtamiace** [comment]
Not deleting profiles and no ability to switch profile was an intentional design.

Summoning @jamalex because I do not remember the rationale :O

**Comment by jtamiace** [comment]
Here is the documentation that _kind of_ touches on that topic

https://docs.google.com/document/d/1tXdOjmLKx9SM12pcMUEosPEV2iQt_FmQtaBn6CUP7hU/edit

**Comment by jtamiace** [comment]
TODO 4 Christ

- Implement immersive full screen bar (like coach report) on the profile selection page, right after "SIGN IN"
- "Who is learning today" --> "Select profile" 
- In side bar & dropdown & URL, "Profile" --> "Account"
- In "Account," "Full name" --> "Profile name"
- 2 separate sections: "Profile" (points, role, name) & "Account" (phone #, change pass field)

**Comment by christianmemije** [comment]
Opened separate issues for each of these #99 #100 #101
